```{r}
library(RTextTools)
library(e1071)
library(qdap)

````



```{r}
pos_tweets = rbind(
  c("A great SEO strategy", "positive"),
  c("A happy #gamedev day :)", "positive"),
  c("A lot of teams don 't even score 62 in a game let alone a half", "positive"),
  c("A quad and a shot in one game Nice :)", "positive"),
  c("A wonderful team wonderful fans - my first CL-game at home was unbeleavable Thanks all :)", "positive"),
  c("Absolutely amazing game by @celtics tonight So proud definitely deserved player ", "positive"),
  c("Absolutely buzzing for WEMBLEY Great game fantastic atmosphere well done", "positive"),
  c("Absolutely loved this cup run and will remember the Chelsea game forever Now let's go get promotion #bcafc", "positive"),
  c("All I can think about it the game :)", "positive"),
  c("All I know is I will be attending this game :)", "positive"),
  c("All I'm saying is it better not rain on Tuesday it's a big game ", "positive"),
  c("All I need in my life is game of thrones", "positive"),
  c("All I wanna do is play my game again  :) http://t co/M6LxY36iB2", "positive"),
  c("All I want in the world is to be at the hockey game right now ", "positive"),
  c("All I want is to watch every single game this year =)", "positive"),
  c("all I want to do is watch game of thrones with some ice cream=)", "positive"),
  c("All is going good", "positive"),
  c("All star game in Toronto next year Wow ", "positive"),
  c("Brady haha What a game he has had =)", "positive"),
  c("Brady has actually been boss this game tbf =)", "positive"),
  c("Brady has been immense this entire game", "positive"),
  c("Brady has done well this game", "positive"),
  c("Brady has had a good game here #LFC ", "positive"),
  c("Already losing my voice because this game is going perfect", "positive"),
  c("Alright #Flyers D it up and close out this game ", "positive"),
  c("Amazing article This is so true ", "positive"),
  c("Amazing Day at work followed by an amazing netball game #lovelife #ThisGirlCan #eventprofs", "positive"),
  c("And you love the game   #TaylorSwift", "positive"),
  c("As I've said you can never have too many rainbows =)", "positive"),
  c("Best game of my life =)", "positive"),
  c("Best game of the year hands down going on", "positive"),
  c("Best game the Blackhawks have played in a long time I hope @spenceelginge1 stays in China for good luck", "positive"),
  c("Congrats @celtics brilliant win Fab game onwards and upwards #proudsponsors", "positive"),
  c("Cool little virtual pin from Nintendo ", "positive"),
  c("cool math game: divide someone's # following by their # of followers that 's the top % of their followers that they don 't think you 're in ", "positive"),
  c("cool new drinking game called take a shot every time someone has a snapchat story with the temperature stamp on it #blacked", "positive"),
  c("Excited for my very first hockey game ", "positive"),
  c("Excited for our game", "positive"),
  c("Good game today Kobe had 20", "positive"),
  c("I love this team Go Bruins!", "positive"),
  c("I love this song", "positive"),
  c("I love this song Miley #Miley =)", "positive"),  
  c("The Internet is amazing =)", "positive"), 
  c("I feel great", "positive"), 
  c("I am so excited about the Miley concert =)",  "positive"), 
  c("She is my best friend", "positive"))
neg_tweets = rbind(
  c("Am I the only girl who hates game of thrones?", "negative"),  
  c("I hate Unity 5  #Unity5", "negative"),  
  c("You just sit in a room and eat the entirety of a package of Mac and cheese on your own ", "negative"),
  c("A word of warning about Unity 5 development #gamedev", "negative"),
  c("Adam Sandler is back to destroy some treasured video game memories in Pixels http://t co/1dIvLj8YYf", "negative"),
  c("Adam Sandler is back to destroy some treasured video game memories in Pixels http://t co/DYhvkbICqD", "negative"),
  c("An absolute joke that someone who takes a hopeless 1-4 team to the playoffs then beats #1 defense doesn 't get to start another NFL game", "negative"),
  c("As if the game wasn 't bad enough", "negative"),
  c("Boise State is choking this game away ", "negative"),
  c("Bradford had been pretty poor all game knew they would never win this one ", "negative"),
  c("Bradford have hardly been in this game", "negative"),
  c("Bradford have outsung Reading all game even at 3-0 down  Proper Yorkshire folk ", "negative"),
  c("Can't afford to lose another game #Celtics", "negative"),
  c("Cliff Lee will never pitch another game in MLB ", "negative"),
  c("Crushing blow for Boise State which has never won an NCAA tournament game ", "negative"),
  c("crying at this game, why? why?  #Celtics", "negative"),
  c("Crying at game now So EMO #Celtics", "negative"),
  c("Denver is resting three starters against their wishes in order to lose a game basically (Ball Don 't Lie): The http://t co/0gfKPKumAg", "negative"),
  c("Dirty players and cheating take the love out of the game #enoughsaid", "negative"),
  c("Celtics has had a poor game #Celtics", "negative"),
  c("Celtics having an sucky type game #Poor ", "negative"),
  c("Celtics having an awful game today ", "negative"),
  c("This game sucked Sorry St Patrick #Celtics", "negative"),
  c("this game sucks none of the Celtics players have even kissed yet", "negative"),
  c("I do not like this song", "negative"),
  c("This song is horrible", "negative"), 
  c("I feel so tired", "negative"),
  c("I am not looking forward to the concert", "negative"),
  c("She sucks", "negative"))

test_tweets = rbind(
  c("Celtics are having a very poor game here", "negative"),
  c("Celtics worst game by far tonight", "negative"),
  c("Celtics positioning is awful so far this game ", "negative"),
  c("The Celtics game is so frustrating", "negative"),
  c("The Celtics game ticks me off sucks", "negative"),
  c("This game still sucks", "negative"),
  c("feel happy this morning", "positive"),
  c("Adam Sandler sucks in Pixels #TheVerge", "negative"),
  c("Adam Sandler is terrible in Pixels", "negative"),
  c("all I can think about is us losing our 2nd playoff game", "negative"),
  c("Excited for our game against LP tmrrw ", "positive"),
  c("Excited for the Barca game tomorrow and el clasico over the weekend", "positive"),
  c("Excited for the game tmrw with my girls  miss everyone @_Jessalynnnn @jaceyjoseph @Eearick19 @shelbynadine96", "positive"),
  c("Good game today by far congratulations", "positive"),
  c("Amazing game #B1GTEN", "positive"),
  c("amazing game between miami and cleveland ", "positive"),
  c("And you love the game", "positive"))



tweets = rbind(pos_tweets, neg_tweets, test_tweets)
tweets
summary(tweets)
n<-length(tweets[,1])
length(test_tweets[,1])

train.n<-length(tweets[,1])-length(test_tweets[,1])
train.n


matrix = create_matrix(tweets[, 1], language = "english", removeStopwords = FALSE, 
                       removeNumbers = TRUE, stemWords = FALSE, tm::weightTfIdf)
mat = as.matrix(matrix)
mat

classifier <- naiveBayes(mat[1:train.n, ], as.factor(tweets[1:train.n, 2]))
predicted <- predict(classifier, mat[(train.n+1):n, ])
predicted
table(tweets[(train.n+1):n, 2], predicted)
recall_accuracy(tweets[(train.n+1):n, 2], predicted)


# Other classification methods.
container = create_container(matrix, as.numeric(as.factor(tweets[, 2])), trainSize = 1:train.n, 
                             testSize = (train.n+1):n, virgin = FALSE)  #removeSparseTerms
models = train_models(container, algorithms = c("MAXENT", "SVM", "RF", "BAGGING", 
                                                "TREE"))
results = classify_models(container, models)
# accuracy
table(as.numeric(as.factor(tweets[(train.n+1):n, 2])), results[, "FORESTS_LABEL"])

table(as.numeric(as.factor(tweets[(train.n+1):n, 2])), results[, "MAXENTROPY_LABEL"])



recall_accuracy(as.numeric(as.factor(tweets[(train.n+1):n, 2])), results[, "FORESTS_LABEL"])
## [1] 0.8235294
recall_accuracy(as.numeric(as.factor(tweets[(train.n+1):n, 2])), results[, "MAXENTROPY_LABEL"])
## [1] 0.9411765
recall_accuracy(as.numeric(as.factor(tweets[(train.n+1):n, 2])), results[, "TREE_LABEL"])
## [1] 0.7647059
recall_accuracy(as.numeric(as.factor(tweets[(train.n+1):n, 2])), results[, "BAGGING_LABEL"])
## [1] 0.9411765
recall_accuracy(as.numeric(as.factor(tweets[(train.n+1):n, 2])), results[, "SVM_LABEL"])
## [1] 0.9411765
# model summary
analytics = create_analytics(container, results)
summary(analytics)


N = 4
set.seed(333 )
cross_validate(container, N, "MAXENT")
cross_validate(container, N, "TREE")


cross_validate(container, N, "SVM")


cross_validate(container, N, "RF")	



text <- tweets[,c(1)]
head(text)
length(text)

ps <- polarity(text)
ps
ps$group
ps$all
```


